#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 18

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_process = 2,
  sym_comment = 3,
  anon_sym_type = 4,
  anon_sym_DOT = 5,
  anon_sym_channel = 6,
  anon_sym_COMMA = 7,
  anon_sym_free = 8,
  anon_sym_COLON = 9,
  anon_sym_let = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_EQ = 13,
  anon_sym_event = 14,
  anon_sym_query = 15,
  anon_sym_SEMI = 16,
  anon_sym_LBRACK = 17,
  anon_sym_private = 18,
  anon_sym_RBRACK = 19,
  anon_sym_PLUS = 20,
  anon_sym_DASH = 21,
  anon_sym_GT = 22,
  anon_sym_LT = 23,
  anon_sym_GT_EQ = 24,
  anon_sym_LT_EQ = 25,
  anon_sym_LT_GT = 26,
  anon_sym_AMP_AMP = 27,
  anon_sym_PIPE_PIPE = 28,
  anon_sym_EQ_EQ_GT = 29,
  anon_sym_0 = 30,
  anon_sym_yield = 31,
  anon_sym_out = 32,
  anon_sym_in = 33,
  sym_source_file = 34,
  sym__declaration = 35,
  sym_type_declaration = 36,
  sym_channel_declaration = 37,
  sym_free_declaration = 38,
  sym_let_declaration = 39,
  sym_event_declaration = 40,
  sym_query_declaration = 41,
  sym_parameter_list = 42,
  sym_typed_parameter_list = 43,
  sym_type_annotation = 44,
  sym__option_list = 45,
  sym_query = 46,
  sym__query_term = 47,
  sym_predicate_term = 48,
  sym_binary_term = 49,
  sym_process = 50,
  sym__atomic_process = 51,
  sym_out_process = 52,
  sym_in_process = 53,
  sym__process_term = 54,
  sym__type_identifier = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_channel_declaration_repeat1 = 57,
  aux_sym_free_declaration_repeat1 = 58,
  aux_sym_parameter_list_repeat1 = 59,
  aux_sym_typed_parameter_list_repeat1 = 60,
  aux_sym__option_list_repeat1 = 61,
  aux_sym_query_repeat1 = 62,
  aux_sym_predicate_term_repeat1 = 63,
  aux_sym_process_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_process] = "process",
  [sym_comment] = "comment",
  [anon_sym_type] = "type",
  [anon_sym_DOT] = ".",
  [anon_sym_channel] = "channel",
  [anon_sym_COMMA] = ",",
  [anon_sym_free] = "free",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_EQ] = "=",
  [anon_sym_event] = "event",
  [anon_sym_query] = "query",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACK] = "[",
  [anon_sym_private] = "private",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_EQ_EQ_GT] = "==>",
  [anon_sym_0] = "0",
  [anon_sym_yield] = "yield",
  [anon_sym_out] = "out",
  [anon_sym_in] = "in",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_type_declaration] = "type_declaration",
  [sym_channel_declaration] = "channel_declaration",
  [sym_free_declaration] = "free_declaration",
  [sym_let_declaration] = "let_declaration",
  [sym_event_declaration] = "event_declaration",
  [sym_query_declaration] = "query_declaration",
  [sym_parameter_list] = "parameter_list",
  [sym_typed_parameter_list] = "typed_parameter_list",
  [sym_type_annotation] = "type_annotation",
  [sym__option_list] = "_option_list",
  [sym_query] = "query",
  [sym__query_term] = "_query_term",
  [sym_predicate_term] = "predicate_term",
  [sym_binary_term] = "binary_term",
  [sym_process] = "process",
  [sym__atomic_process] = "_atomic_process",
  [sym_out_process] = "out_process",
  [sym_in_process] = "in_process",
  [sym__process_term] = "_process_term",
  [sym__type_identifier] = "_type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_channel_declaration_repeat1] = "channel_declaration_repeat1",
  [aux_sym_free_declaration_repeat1] = "free_declaration_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_typed_parameter_list_repeat1] = "typed_parameter_list_repeat1",
  [aux_sym__option_list_repeat1] = "_option_list_repeat1",
  [aux_sym_query_repeat1] = "query_repeat1",
  [aux_sym_predicate_term_repeat1] = "predicate_term_repeat1",
  [aux_sym_process_repeat1] = "process_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_process] = anon_sym_process,
  [sym_comment] = sym_comment,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_channel] = anon_sym_channel,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_free] = anon_sym_free,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_event] = anon_sym_event,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_EQ_EQ_GT] = anon_sym_EQ_EQ_GT,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_yield] = anon_sym_yield,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_in] = anon_sym_in,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_type_declaration] = sym_type_declaration,
  [sym_channel_declaration] = sym_channel_declaration,
  [sym_free_declaration] = sym_free_declaration,
  [sym_let_declaration] = sym_let_declaration,
  [sym_event_declaration] = sym_event_declaration,
  [sym_query_declaration] = sym_query_declaration,
  [sym_parameter_list] = sym_parameter_list,
  [sym_typed_parameter_list] = sym_typed_parameter_list,
  [sym_type_annotation] = sym_type_annotation,
  [sym__option_list] = sym__option_list,
  [sym_query] = sym_query,
  [sym__query_term] = sym__query_term,
  [sym_predicate_term] = sym_predicate_term,
  [sym_binary_term] = sym_binary_term,
  [sym_process] = sym_process,
  [sym__atomic_process] = sym__atomic_process,
  [sym_out_process] = sym_out_process,
  [sym_in_process] = sym_in_process,
  [sym__process_term] = sym__process_term,
  [sym__type_identifier] = sym__type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_channel_declaration_repeat1] = aux_sym_channel_declaration_repeat1,
  [aux_sym_free_declaration_repeat1] = aux_sym_free_declaration_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_typed_parameter_list_repeat1] = aux_sym_typed_parameter_list_repeat1,
  [aux_sym__option_list_repeat1] = aux_sym__option_list_repeat1,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
  [aux_sym_predicate_term_repeat1] = aux_sym_predicate_term_repeat1,
  [aux_sym_process_repeat1] = aux_sym_process_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_process] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_channel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_free] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_event] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yield] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_channel_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_free_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_let_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_event_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_query_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_typed_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym__option_list] = {
    .visible = false,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym__query_term] = {
    .visible = false,
    .named = true,
  },
  [sym_predicate_term] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_process] = {
    .visible = true,
    .named = true,
  },
  [sym__atomic_process] = {
    .visible = false,
    .named = true,
  },
  [sym_out_process] = {
    .visible = true,
    .named = true,
  },
  [sym_in_process] = {
    .visible = true,
    .named = true,
  },
  [sym__process_term] = {
    .visible = false,
    .named = true,
  },
  [sym__type_identifier] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_channel_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_free_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_typed_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__option_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_predicate_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_process_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_channel = 1,
  field_left = 2,
  field_message = 3,
  field_name = 4,
  field_operator = 5,
  field_options = 6,
  field_parameter = 7,
  field_parameters = 8,
  field_predicate = 9,
  field_process = 10,
  field_query = 11,
  field_right = 12,
  field_type = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_channel] = "channel",
  [field_left] = "left",
  [field_message] = "message",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_options] = "options",
  [field_parameter] = "parameter",
  [field_parameters] = "parameters",
  [field_predicate] = "predicate",
  [field_process] = "process",
  [field_query] = "query",
  [field_right] = "right",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 3},
  [7] = {.index = 11, .length = 2},
  [8] = {.index = 13, .length = 2},
  [9] = {.index = 15, .length = 2},
  [10] = {.index = 17, .length = 3},
  [11] = {.index = 20, .length = 2},
  [12] = {.index = 22, .length = 3},
  [13] = {.index = 25, .length = 2},
  [14] = {.index = 27, .length = 3},
  [15] = {.index = 30, .length = 3},
  [16] = {.index = 33, .length = 2},
  [17] = {.index = 35, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_query, 1},
  [2] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [4] =
    {field_name, 0},
    {field_type, 2},
  [6] =
    {field_options, 2},
    {field_query, 1},
  [8] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [11] =
    {field_name, 1},
    {field_type, 3},
  [13] =
    {field_name, 1},
    {field_process, 3},
  [15] =
    {field_parameter, 2},
    {field_predicate, 0},
  [17] =
    {field_name, 0},
    {field_name, 1, .inherited = true},
    {field_type, 3},
  [20] =
    {field_parameters, 1},
    {field_query, 3},
  [22] =
    {field_name, 1},
    {field_name, 2, .inherited = true},
    {field_type, 4},
  [25] =
    {field_name, 1},
    {field_parameters, 3},
  [27] =
    {field_parameter, 2},
    {field_parameter, 3},
    {field_predicate, 0},
  [30] =
    {field_options, 4},
    {field_parameters, 1},
    {field_query, 3},
  [33] =
    {field_channel, 2},
    {field_message, 4},
  [35] =
    {field_name, 1},
    {field_parameters, 3},
    {field_process, 6},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ')') ADVANCE(22);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '0') ADVANCE(38);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == ';') ADVANCE(24);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(49);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead == 'y') ADVANCE(47);
      if (lookahead == '|') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\'' ||
          ('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(13);
      if (lookahead == 'y') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '|') ADVANCE(35);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '(') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15)
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(6);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_0);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_yield);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_yield);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_out);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(40);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(44);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(42);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(50);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 'q') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_free);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 'y') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_event);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_channel);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_process);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 15},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 15},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 15},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 15},
  [46] = {.lex_state = 15},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 15},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 15},
  [56] = {.lex_state = 15},
  [57] = {.lex_state = 15},
  [58] = {.lex_state = 15},
  [59] = {.lex_state = 15},
  [60] = {.lex_state = 15},
  [61] = {.lex_state = 15},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 15},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 15},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 15},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 15},
  [92] = {.lex_state = 15},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 15},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 15},
  [99] = {.lex_state = 15},
  [100] = {.lex_state = 15},
  [101] = {.lex_state = 15},
  [102] = {.lex_state = 15},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 15},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 15},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 15},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 15},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 15},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 15},
  [133] = {.lex_state = 15},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 15},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_process] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_channel] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_free] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_event] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_EQ_EQ_GT] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_yield] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(129),
    [sym__declaration] = STATE(4),
    [sym_type_declaration] = STATE(4),
    [sym_channel_declaration] = STATE(4),
    [sym_free_declaration] = STATE(4),
    [sym_let_declaration] = STATE(4),
    [sym_event_declaration] = STATE(4),
    [sym_query_declaration] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_process] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_channel] = ACTIONS(11),
    [anon_sym_free] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(15),
    [anon_sym_event] = ACTIONS(17),
    [anon_sym_query] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_COLON,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    STATE(90), 1,
      aux_sym_free_declaration_repeat1,
    ACTIONS(29), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(21), 11,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [34] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(21), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [61] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      anon_sym_channel,
    ACTIONS(13), 1,
      anon_sym_free,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_event,
    ACTIONS(19), 1,
      anon_sym_query,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(33), 1,
      anon_sym_process,
    STATE(16), 8,
      sym__declaration,
      sym_type_declaration,
      sym_channel_declaration,
      sym_free_declaration,
      sym_let_declaration,
      sym_event_declaration,
      sym_query_declaration,
      aux_sym_source_file_repeat1,
  [99] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 8,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [135] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(51), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [159] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(35), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [183] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 8,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [219] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(37), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(35), 11,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [245] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(37), 2,
      anon_sym_EQ,
      anon_sym_LT,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 11,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [273] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 11,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [303] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 10,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [335] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(57), 1,
      anon_sym_AMP_AMP,
    ACTIONS(59), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 6,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_EQ_EQ_GT,
  [375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(61), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [399] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [433] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_type,
    ACTIONS(70), 1,
      anon_sym_channel,
    ACTIONS(73), 1,
      anon_sym_free,
    ACTIONS(76), 1,
      anon_sym_let,
    ACTIONS(79), 1,
      anon_sym_event,
    ACTIONS(82), 1,
      anon_sym_query,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_process,
    STATE(16), 8,
      sym__declaration,
      sym_type_declaration,
      sym_channel_declaration,
      sym_free_declaration,
      sym_let_declaration,
      sym_event_declaration,
      sym_query_declaration,
      aux_sym_source_file_repeat1,
  [469] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(57), 1,
      anon_sym_AMP_AMP,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(35), 7,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [507] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(57), 1,
      anon_sym_AMP_AMP,
    ACTIONS(59), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    STATE(62), 1,
      aux_sym_query_repeat1,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(85), 2,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [552] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(57), 1,
      anon_sym_AMP_AMP,
    ACTIONS(59), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
  [592] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(57), 1,
      anon_sym_AMP_AMP,
    ACTIONS(59), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_predicate_term_repeat1,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [636] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_GT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(55), 1,
      anon_sym_EQ,
    ACTIONS(57), 1,
      anon_sym_AMP_AMP,
    ACTIONS(59), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(39), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(97), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [745] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [759] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [773] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_out,
    ACTIONS(117), 1,
      anon_sym_in,
    STATE(131), 1,
      sym_process,
    ACTIONS(113), 2,
      anon_sym_0,
      anon_sym_yield,
    STATE(48), 3,
      sym__atomic_process,
      sym_out_process,
      sym_in_process,
  [795] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [809] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [823] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [837] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [851] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_out,
    ACTIONS(117), 1,
      anon_sym_in,
    STATE(123), 1,
      sym_process,
    ACTIONS(113), 2,
      anon_sym_0,
      anon_sym_yield,
    STATE(48), 3,
      sym__atomic_process,
      sym_out_process,
      sym_in_process,
  [873] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [887] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [901] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [915] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_out,
    ACTIONS(117), 1,
      anon_sym_in,
    STATE(139), 1,
      sym_process,
    ACTIONS(113), 2,
      anon_sym_0,
      anon_sym_yield,
    STATE(48), 3,
      sym__atomic_process,
      sym_out_process,
      sym_in_process,
  [937] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_out,
    ACTIONS(117), 1,
      anon_sym_in,
    STATE(136), 1,
      sym_process,
    ACTIONS(113), 2,
      anon_sym_0,
      anon_sym_yield,
    STATE(48), 3,
      sym__atomic_process,
      sym_out_process,
      sym_in_process,
  [959] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [973] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      sym_identifier,
    STATE(63), 1,
      sym_type_annotation,
    STATE(89), 1,
      sym_query,
    STATE(109), 1,
      sym_typed_parameter_list,
    STATE(18), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [994] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      anon_sym_out,
    ACTIONS(117), 1,
      anon_sym_in,
    ACTIONS(137), 2,
      anon_sym_0,
      anon_sym_yield,
    STATE(69), 3,
      sym__atomic_process,
      sym_out_process,
      sym_in_process,
  [1013] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(84), 1,
      sym_query,
    STATE(18), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1028] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(20), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1040] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(21), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1052] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(79), 1,
      sym__type_identifier,
    STATE(135), 1,
      sym_parameter_list,
    ACTIONS(141), 2,
      anon_sym_channel,
      sym_identifier,
  [1066] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_typed_parameter_list_repeat1,
    ACTIONS(145), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1080] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_SEMI,
    STATE(50), 1,
      aux_sym_process_repeat1,
    ACTIONS(147), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1094] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_typed_parameter_list_repeat1,
    ACTIONS(154), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1108] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      aux_sym_process_repeat1,
    ACTIONS(156), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1122] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(5), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1134] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(19), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1146] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1158] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(9), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1170] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(10), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1182] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(11), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1194] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(12), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1206] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(15), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1218] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(8), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1230] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(17), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1242] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(13), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1254] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      aux_sym_query_repeat1,
    ACTIONS(158), 2,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1268] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_COMMA,
    STATE(47), 1,
      aux_sym_typed_parameter_list_repeat1,
    ACTIONS(160), 2,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1282] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      aux_sym_process_repeat1,
    ACTIONS(162), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1296] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      aux_sym_query_repeat1,
    ACTIONS(91), 2,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1310] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_DOT,
    ACTIONS(172), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_channel_declaration_repeat1,
  [1323] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      aux_sym__option_list_repeat1,
  [1336] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
  [1345] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
  [1354] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(181), 1,
      anon_sym_COLON,
    STATE(93), 1,
      aux_sym_free_declaration_repeat1,
  [1367] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_parameter_list_repeat1,
  [1380] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 1,
      anon_sym_DOT,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    STATE(111), 1,
      sym__option_list,
  [1393] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(86), 1,
      sym__type_identifier,
    ACTIONS(191), 2,
      anon_sym_channel,
      sym_identifier,
  [1404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(196), 1,
      anon_sym_COLON,
    STATE(74), 1,
      aux_sym_free_declaration_repeat1,
  [1417] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_COLON,
    STATE(90), 1,
      aux_sym_free_declaration_repeat1,
  [1430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
  [1439] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym__option_list_repeat1,
  [1452] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(103), 1,
      sym__type_identifier,
    ACTIONS(205), 2,
      anon_sym_channel,
      sym_identifier,
  [1463] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 1,
      anon_sym_COMMA,
    ACTIONS(207), 1,
      anon_sym_RPAREN,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1476] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(209), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1485] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(211), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_predicate_term_repeat1,
  [1498] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym_parameter_list_repeat1,
  [1511] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(97), 1,
      sym__type_identifier,
    ACTIONS(219), 2,
      anon_sym_channel,
      sym_identifier,
  [1522] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    ACTIONS(221), 1,
      anon_sym_DOT,
    STATE(116), 1,
      sym__option_list,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1544] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    ACTIONS(223), 1,
      anon_sym_DOT,
    STATE(124), 1,
      sym__option_list,
  [1557] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym_predicate_term_repeat1,
  [1570] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 1,
      anon_sym_COMMA,
    ACTIONS(227), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym__option_list_repeat1,
  [1583] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_LBRACK,
    ACTIONS(229), 1,
      anon_sym_DOT,
    STATE(128), 1,
      sym__option_list,
  [1596] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(231), 1,
      anon_sym_COLON,
    STATE(74), 1,
      aux_sym_free_declaration_repeat1,
  [1609] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(80), 1,
      sym__type_identifier,
    ACTIONS(233), 2,
      anon_sym_channel,
      sym_identifier,
  [1620] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(63), 1,
      sym_type_annotation,
    STATE(137), 1,
      sym_typed_parameter_list,
  [1633] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(237), 1,
      anon_sym_COLON,
    STATE(74), 1,
      aux_sym_free_declaration_repeat1,
  [1646] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(72), 1,
      sym__type_identifier,
    ACTIONS(239), 2,
      anon_sym_channel,
      sym_identifier,
  [1657] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_DOT,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    STATE(96), 1,
      aux_sym_channel_declaration_repeat1,
  [1670] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_DOT,
    STATE(66), 1,
      aux_sym_channel_declaration_repeat1,
  [1683] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 3,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_SEMI,
  [1692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      sym_identifier,
    STATE(114), 1,
      sym__process_term,
  [1702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      sym_identifier,
    STATE(113), 1,
      sym__process_term,
  [1712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(235), 1,
      sym_identifier,
    STATE(85), 1,
      sym_type_annotation,
  [1722] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      sym_identifier,
    STATE(120), 1,
      sym__process_term,
  [1732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(121), 1,
      sym__process_term,
  [1742] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(217), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1750] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_DOT,
    ACTIONS(259), 1,
      anon_sym_LPAREN,
  [1760] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1768] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 2,
      anon_sym_COMMA,
      anon_sym_COLON,
  [1776] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(263), 1,
      anon_sym_LPAREN,
    ACTIONS(265), 1,
      anon_sym_EQ,
  [1786] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1794] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(267), 1,
      anon_sym_SEMI,
  [1801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 1,
      anon_sym_EQ,
  [1808] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 1,
      anon_sym_DOT,
  [1815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 1,
      anon_sym_DOT,
  [1822] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 1,
      anon_sym_COMMA,
  [1829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COMMA,
  [1836] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_identifier,
  [1843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      anon_sym_DOT,
  [1850] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_private,
  [1857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      anon_sym_DOT,
  [1864] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
  [1871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
  [1878] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_RPAREN,
  [1885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_DOT,
  [1892] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      ts_builtin_sym_end,
  [1899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      anon_sym_DOT,
  [1906] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(299), 1,
      anon_sym_LPAREN,
  [1913] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(301), 1,
      anon_sym_LPAREN,
  [1920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(303), 1,
      anon_sym_private,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_DOT,
  [1934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(307), 1,
      ts_builtin_sym_end,
  [1941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(309), 1,
      sym_identifier,
  [1948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(311), 1,
      ts_builtin_sym_end,
  [1955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      sym_identifier,
  [1962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(315), 1,
      sym_identifier,
  [1969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(317), 1,
      anon_sym_DOT,
  [1976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
  [1983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_DOT,
  [1990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(323), 1,
      anon_sym_RPAREN,
  [1997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(325), 1,
      sym_identifier,
  [2004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(327), 1,
      anon_sym_DOT,
  [2011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(329), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 61,
  [SMALL_STATE(5)] = 99,
  [SMALL_STATE(6)] = 135,
  [SMALL_STATE(7)] = 159,
  [SMALL_STATE(8)] = 183,
  [SMALL_STATE(9)] = 219,
  [SMALL_STATE(10)] = 245,
  [SMALL_STATE(11)] = 273,
  [SMALL_STATE(12)] = 303,
  [SMALL_STATE(13)] = 335,
  [SMALL_STATE(14)] = 375,
  [SMALL_STATE(15)] = 399,
  [SMALL_STATE(16)] = 433,
  [SMALL_STATE(17)] = 469,
  [SMALL_STATE(18)] = 507,
  [SMALL_STATE(19)] = 552,
  [SMALL_STATE(20)] = 592,
  [SMALL_STATE(21)] = 636,
  [SMALL_STATE(22)] = 675,
  [SMALL_STATE(23)] = 689,
  [SMALL_STATE(24)] = 703,
  [SMALL_STATE(25)] = 717,
  [SMALL_STATE(26)] = 731,
  [SMALL_STATE(27)] = 745,
  [SMALL_STATE(28)] = 759,
  [SMALL_STATE(29)] = 773,
  [SMALL_STATE(30)] = 795,
  [SMALL_STATE(31)] = 809,
  [SMALL_STATE(32)] = 823,
  [SMALL_STATE(33)] = 837,
  [SMALL_STATE(34)] = 851,
  [SMALL_STATE(35)] = 873,
  [SMALL_STATE(36)] = 887,
  [SMALL_STATE(37)] = 901,
  [SMALL_STATE(38)] = 915,
  [SMALL_STATE(39)] = 937,
  [SMALL_STATE(40)] = 959,
  [SMALL_STATE(41)] = 973,
  [SMALL_STATE(42)] = 994,
  [SMALL_STATE(43)] = 1013,
  [SMALL_STATE(44)] = 1028,
  [SMALL_STATE(45)] = 1040,
  [SMALL_STATE(46)] = 1052,
  [SMALL_STATE(47)] = 1066,
  [SMALL_STATE(48)] = 1080,
  [SMALL_STATE(49)] = 1094,
  [SMALL_STATE(50)] = 1108,
  [SMALL_STATE(51)] = 1122,
  [SMALL_STATE(52)] = 1134,
  [SMALL_STATE(53)] = 1146,
  [SMALL_STATE(54)] = 1158,
  [SMALL_STATE(55)] = 1170,
  [SMALL_STATE(56)] = 1182,
  [SMALL_STATE(57)] = 1194,
  [SMALL_STATE(58)] = 1206,
  [SMALL_STATE(59)] = 1218,
  [SMALL_STATE(60)] = 1230,
  [SMALL_STATE(61)] = 1242,
  [SMALL_STATE(62)] = 1254,
  [SMALL_STATE(63)] = 1268,
  [SMALL_STATE(64)] = 1282,
  [SMALL_STATE(65)] = 1296,
  [SMALL_STATE(66)] = 1310,
  [SMALL_STATE(67)] = 1323,
  [SMALL_STATE(68)] = 1336,
  [SMALL_STATE(69)] = 1345,
  [SMALL_STATE(70)] = 1354,
  [SMALL_STATE(71)] = 1367,
  [SMALL_STATE(72)] = 1380,
  [SMALL_STATE(73)] = 1393,
  [SMALL_STATE(74)] = 1404,
  [SMALL_STATE(75)] = 1417,
  [SMALL_STATE(76)] = 1430,
  [SMALL_STATE(77)] = 1439,
  [SMALL_STATE(78)] = 1452,
  [SMALL_STATE(79)] = 1463,
  [SMALL_STATE(80)] = 1476,
  [SMALL_STATE(81)] = 1485,
  [SMALL_STATE(82)] = 1498,
  [SMALL_STATE(83)] = 1511,
  [SMALL_STATE(84)] = 1522,
  [SMALL_STATE(85)] = 1535,
  [SMALL_STATE(86)] = 1544,
  [SMALL_STATE(87)] = 1557,
  [SMALL_STATE(88)] = 1570,
  [SMALL_STATE(89)] = 1583,
  [SMALL_STATE(90)] = 1596,
  [SMALL_STATE(91)] = 1609,
  [SMALL_STATE(92)] = 1620,
  [SMALL_STATE(93)] = 1633,
  [SMALL_STATE(94)] = 1646,
  [SMALL_STATE(95)] = 1657,
  [SMALL_STATE(96)] = 1670,
  [SMALL_STATE(97)] = 1683,
  [SMALL_STATE(98)] = 1692,
  [SMALL_STATE(99)] = 1702,
  [SMALL_STATE(100)] = 1712,
  [SMALL_STATE(101)] = 1722,
  [SMALL_STATE(102)] = 1732,
  [SMALL_STATE(103)] = 1742,
  [SMALL_STATE(104)] = 1750,
  [SMALL_STATE(105)] = 1760,
  [SMALL_STATE(106)] = 1768,
  [SMALL_STATE(107)] = 1776,
  [SMALL_STATE(108)] = 1786,
  [SMALL_STATE(109)] = 1794,
  [SMALL_STATE(110)] = 1801,
  [SMALL_STATE(111)] = 1808,
  [SMALL_STATE(112)] = 1815,
  [SMALL_STATE(113)] = 1822,
  [SMALL_STATE(114)] = 1829,
  [SMALL_STATE(115)] = 1836,
  [SMALL_STATE(116)] = 1843,
  [SMALL_STATE(117)] = 1850,
  [SMALL_STATE(118)] = 1857,
  [SMALL_STATE(119)] = 1864,
  [SMALL_STATE(120)] = 1871,
  [SMALL_STATE(121)] = 1878,
  [SMALL_STATE(122)] = 1885,
  [SMALL_STATE(123)] = 1892,
  [SMALL_STATE(124)] = 1899,
  [SMALL_STATE(125)] = 1906,
  [SMALL_STATE(126)] = 1913,
  [SMALL_STATE(127)] = 1920,
  [SMALL_STATE(128)] = 1927,
  [SMALL_STATE(129)] = 1934,
  [SMALL_STATE(130)] = 1941,
  [SMALL_STATE(131)] = 1948,
  [SMALL_STATE(132)] = 1955,
  [SMALL_STATE(133)] = 1962,
  [SMALL_STATE(134)] = 1969,
  [SMALL_STATE(135)] = 1976,
  [SMALL_STATE(136)] = 1983,
  [SMALL_STATE(137)] = 1990,
  [SMALL_STATE(138)] = 1997,
  [SMALL_STATE(139)] = 2004,
  [SMALL_STATE(140)] = 2011,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query_term, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__query_term, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_term, 3, .production_id = 6),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_term, 3, .production_id = 6),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_term, 5, .production_id = 14),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate_term, 5, .production_id = 14),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_term, 4, .production_id = 9),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate_term, 4, .production_id = 9),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(133),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(140),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(138),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(132),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(130),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(41),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicate_term_repeat1, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 3, .production_id = 1),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_declaration, 3),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 8, .production_id = 17),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 5, .production_id = 8),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 5, .production_id = 7),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 7, .production_id = 12),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 6, .production_id = 15),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 5, .production_id = 11),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 3, .production_id = 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_declaration, 4),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_declaration, 6, .production_id = 13),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 4, .production_id = 5),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 6, .production_id = 7),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 6, .production_id = 12),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_declaration, 3, .production_id = 1),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_parameter_list, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_typed_parameter_list_repeat1, 2), SHIFT_REPEAT(100),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_typed_parameter_list_repeat1, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_parameter_list, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_process_repeat1, 2),
  [164] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_process_repeat1, 2), SHIFT_REPEAT(42),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2), SHIFT_REPEAT(52),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_channel_declaration_repeat1, 2),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_channel_declaration_repeat1, 2), SHIFT_REPEAT(115),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_in_process, 6, .production_id = 16),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [191] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_free_declaration_repeat1, 2, .production_id = 3), SHIFT_REPEAT(119),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_free_declaration_repeat1, 2, .production_id = 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_process, 6, .production_id = 16),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__option_list_repeat1, 2), SHIFT_REPEAT(117),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__option_list_repeat1, 2),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 3, .production_id = 4),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_term_repeat1, 2), SHIFT_REPEAT(45),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(78),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [233] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 4, .production_id = 10),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [259] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_free_declaration_repeat1, 2, .production_id = 1),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__option_list, 3),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [307] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__option_list, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_proverif() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
