#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 146
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 24

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_process = 2,
  sym_comment = 3,
  anon_sym_type = 4,
  anon_sym_DOT = 5,
  anon_sym_channel = 6,
  anon_sym_COMMA = 7,
  anon_sym_free = 8,
  anon_sym_COLON = 9,
  anon_sym_let = 10,
  anon_sym_EQ = 11,
  anon_sym_event = 12,
  anon_sym_query = 13,
  anon_sym_SEMI = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LBRACK = 17,
  anon_sym_private = 18,
  anon_sym_RBRACK = 19,
  anon_sym_PLUS = 20,
  anon_sym_DASH = 21,
  anon_sym_GT = 22,
  anon_sym_LT = 23,
  anon_sym_GT_EQ = 24,
  anon_sym_LT_EQ = 25,
  anon_sym_LT_GT = 26,
  anon_sym_AMP_AMP = 27,
  anon_sym_PIPE_PIPE = 28,
  anon_sym_EQ_EQ_GT = 29,
  anon_sym_0 = 30,
  anon_sym_yield = 31,
  anon_sym_in = 32,
  anon_sym_out = 33,
  sym_source_file = 34,
  sym__declaration = 35,
  sym_type_declaration = 36,
  sym_channel_declaration = 37,
  sym_free_declaration = 38,
  sym_let_declaration = 39,
  sym_event_declaration = 40,
  sym_query_declaration = 41,
  sym_type_list = 42,
  sym_parameter_list = 43,
  sym_type_annotation = 44,
  sym_option_list = 45,
  sym_query = 46,
  sym__query_term = 47,
  sym_predicate_term = 48,
  sym_binary_term = 49,
  sym_process = 50,
  sym_message_process = 51,
  sym__process_term = 52,
  sym__type_identifier = 53,
  aux_sym_source_file_repeat1 = 54,
  aux_sym_channel_declaration_repeat1 = 55,
  aux_sym_free_declaration_repeat1 = 56,
  aux_sym_query_declaration_repeat1 = 57,
  aux_sym_type_list_repeat1 = 58,
  aux_sym_parameter_list_repeat1 = 59,
  aux_sym_option_list_repeat1 = 60,
  aux_sym_query_repeat1 = 61,
  aux_sym_predicate_term_repeat1 = 62,
  aux_sym_process_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_process] = "process",
  [sym_comment] = "comment",
  [anon_sym_type] = "type",
  [anon_sym_DOT] = ".",
  [anon_sym_channel] = "channel",
  [anon_sym_COMMA] = ",",
  [anon_sym_free] = "free",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_event] = "event",
  [anon_sym_query] = "query",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_private] = "identifier",
  [anon_sym_RBRACK] = "]",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_EQ_EQ_GT] = "==>",
  [anon_sym_0] = "0",
  [anon_sym_yield] = "yield",
  [anon_sym_in] = "in",
  [anon_sym_out] = "out",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_type_declaration] = "type_declaration",
  [sym_channel_declaration] = "channel_declaration",
  [sym_free_declaration] = "free_declaration",
  [sym_let_declaration] = "let_declaration",
  [sym_event_declaration] = "event_declaration",
  [sym_query_declaration] = "query_declaration",
  [sym_type_list] = "type_list",
  [sym_parameter_list] = "parameter_list",
  [sym_type_annotation] = "type_annotation",
  [sym_option_list] = "option_list",
  [sym_query] = "query",
  [sym__query_term] = "_query_term",
  [sym_predicate_term] = "predicate_term",
  [sym_binary_term] = "binary_term",
  [sym_process] = "process",
  [sym_message_process] = "message_process",
  [sym__process_term] = "_process_term",
  [sym__type_identifier] = "_type_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_channel_declaration_repeat1] = "channel_declaration_repeat1",
  [aux_sym_free_declaration_repeat1] = "free_declaration_repeat1",
  [aux_sym_query_declaration_repeat1] = "query_declaration_repeat1",
  [aux_sym_type_list_repeat1] = "type_list_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_option_list_repeat1] = "option_list_repeat1",
  [aux_sym_query_repeat1] = "query_repeat1",
  [aux_sym_predicate_term_repeat1] = "predicate_term_repeat1",
  [aux_sym_process_repeat1] = "process_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_process] = anon_sym_process,
  [sym_comment] = sym_comment,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_channel] = anon_sym_channel,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_free] = anon_sym_free,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_event] = anon_sym_event,
  [anon_sym_query] = anon_sym_query,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_private] = sym_identifier,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_EQ_EQ_GT] = anon_sym_EQ_EQ_GT,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_yield] = anon_sym_yield,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_out] = anon_sym_out,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_type_declaration] = sym_type_declaration,
  [sym_channel_declaration] = sym_channel_declaration,
  [sym_free_declaration] = sym_free_declaration,
  [sym_let_declaration] = sym_let_declaration,
  [sym_event_declaration] = sym_event_declaration,
  [sym_query_declaration] = sym_query_declaration,
  [sym_type_list] = sym_type_list,
  [sym_parameter_list] = sym_parameter_list,
  [sym_type_annotation] = sym_type_annotation,
  [sym_option_list] = sym_option_list,
  [sym_query] = sym_query,
  [sym__query_term] = sym__query_term,
  [sym_predicate_term] = sym_predicate_term,
  [sym_binary_term] = sym_binary_term,
  [sym_process] = sym_process,
  [sym_message_process] = sym_message_process,
  [sym__process_term] = sym__process_term,
  [sym__type_identifier] = sym__type_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_channel_declaration_repeat1] = aux_sym_channel_declaration_repeat1,
  [aux_sym_free_declaration_repeat1] = aux_sym_free_declaration_repeat1,
  [aux_sym_query_declaration_repeat1] = aux_sym_query_declaration_repeat1,
  [aux_sym_type_list_repeat1] = aux_sym_type_list_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_option_list_repeat1] = aux_sym_option_list_repeat1,
  [aux_sym_query_repeat1] = aux_sym_query_repeat1,
  [aux_sym_predicate_term_repeat1] = aux_sym_predicate_term_repeat1,
  [aux_sym_process_repeat1] = aux_sym_process_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_process] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_channel] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_free] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_event] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_query] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yield] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_type_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_channel_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_free_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_let_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_event_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_query_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_option_list] = {
    .visible = true,
    .named = true,
  },
  [sym_query] = {
    .visible = true,
    .named = true,
  },
  [sym__query_term] = {
    .visible = false,
    .named = true,
  },
  [sym_predicate_term] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_term] = {
    .visible = true,
    .named = true,
  },
  [sym_process] = {
    .visible = true,
    .named = true,
  },
  [sym_message_process] = {
    .visible = true,
    .named = true,
  },
  [sym__process_term] = {
    .visible = false,
    .named = true,
  },
  [sym__type_identifier] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_channel_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_free_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_type_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_option_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_query_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_predicate_term_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_process_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_binding = 1,
  field_channel = 2,
  field_direction = 3,
  field_left = 4,
  field_message = 5,
  field_name = 6,
  field_operator = 7,
  field_options = 8,
  field_parameter = 9,
  field_parameters = 10,
  field_predicate = 11,
  field_process = 12,
  field_query = 13,
  field_right = 14,
  field_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_binding] = "binding",
  [field_channel] = "channel",
  [field_direction] = "direction",
  [field_left] = "left",
  [field_message] = "message",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_options] = "options",
  [field_parameter] = "parameter",
  [field_parameters] = "parameters",
  [field_predicate] = "predicate",
  [field_process] = "process",
  [field_query] = "query",
  [field_right] = "right",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 2},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 3},
  [14] = {.index = 25, .length = 2},
  [15] = {.index = 27, .length = 3},
  [16] = {.index = 30, .length = 3},
  [17] = {.index = 33, .length = 3},
  [18] = {.index = 36, .length = 3},
  [19] = {.index = 39, .length = 3},
  [20] = {.index = 42, .length = 3},
  [21] = {.index = 45, .length = 3},
  [22] = {.index = 48, .length = 4},
  [23] = {.index = 52, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_query, 1},
  [2] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [4] =
    {field_name, 1},
    {field_parameters, 2},
  [6] =
    {field_name, 0},
    {field_type, 2},
  [8] =
    {field_binding, 1},
  [9] =
    {field_binding, 0, .inherited = true},
    {field_binding, 1, .inherited = true},
  [11] =
    {field_options, 2},
    {field_query, 1},
  [13] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [16] =
    {field_name, 1},
    {field_type, 3},
  [18] =
    {field_name, 1},
    {field_process, 3},
  [20] =
    {field_parameter, 2},
    {field_predicate, 0},
  [22] =
    {field_name, 0},
    {field_name, 1, .inherited = true},
    {field_type, 3},
  [25] =
    {field_binding, 1},
    {field_query, 3},
  [27] =
    {field_name, 1},
    {field_options, 4},
    {field_type, 3},
  [30] =
    {field_name, 1},
    {field_name, 2, .inherited = true},
    {field_type, 4},
  [33] =
    {field_name, 1},
    {field_parameters, 2},
    {field_process, 4},
  [36] =
    {field_parameter, 2},
    {field_parameter, 3},
    {field_predicate, 0},
  [39] =
    {field_binding, 1},
    {field_options, 4},
    {field_query, 3},
  [42] =
    {field_binding, 1},
    {field_binding, 2, .inherited = true},
    {field_query, 4},
  [45] =
    {field_channel, 2},
    {field_direction, 0},
    {field_message, 4},
  [48] =
    {field_name, 1},
    {field_name, 2, .inherited = true},
    {field_options, 5},
    {field_type, 4},
  [52] =
    {field_binding, 1},
    {field_binding, 2, .inherited = true},
    {field_options, 5},
    {field_query, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 144,
  [145] = 145,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      if (lookahead == '&') ADVANCE(1);
      if (lookahead == '(') ADVANCE(23);
      if (lookahead == ')') ADVANCE(24);
      if (lookahead == '+') ADVANCE(27);
      if (lookahead == ',') ADVANCE(19);
      if (lookahead == '-') ADVANCE(28);
      if (lookahead == '.') ADVANCE(18);
      if (lookahead == '0') ADVANCE(38);
      if (lookahead == ':') ADVANCE(20);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '=') ADVANCE(21);
      if (lookahead == '>') ADVANCE(29);
      if (lookahead == '[') ADVANCE(25);
      if (lookahead == ']') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(49);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead == 'y') ADVANCE(47);
      if (lookahead == '|') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      if (lookahead == '\'' ||
          ('1' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '&') ADVANCE(34);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '0') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == 'o') ADVANCE(13);
      if (lookahead == 'y') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(17);
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == '|') ADVANCE(35);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '(') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(15)
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(6);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == '*') ADVANCE(5);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(33);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_0);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_yield);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_yield);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_in);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_out);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(40);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(46);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(45);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(42);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(50);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 'q') ADVANCE(6);
      if (lookahead == 't') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == 'y') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_free);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 'y') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_event);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_query);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(38);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_channel);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_process);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 15},
  [23] = {.lex_state = 15},
  [24] = {.lex_state = 15},
  [25] = {.lex_state = 15},
  [26] = {.lex_state = 15},
  [27] = {.lex_state = 15},
  [28] = {.lex_state = 15},
  [29] = {.lex_state = 15},
  [30] = {.lex_state = 15},
  [31] = {.lex_state = 15},
  [32] = {.lex_state = 15},
  [33] = {.lex_state = 15},
  [34] = {.lex_state = 15},
  [35] = {.lex_state = 15},
  [36] = {.lex_state = 15},
  [37] = {.lex_state = 15},
  [38] = {.lex_state = 15},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 15},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 15},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 15},
  [47] = {.lex_state = 15},
  [48] = {.lex_state = 15},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 15},
  [51] = {.lex_state = 15},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 15},
  [54] = {.lex_state = 15},
  [55] = {.lex_state = 15},
  [56] = {.lex_state = 15},
  [57] = {.lex_state = 15},
  [58] = {.lex_state = 15},
  [59] = {.lex_state = 15},
  [60] = {.lex_state = 15},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 15},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 15},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 15},
  [81] = {.lex_state = 15},
  [82] = {.lex_state = 15},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 15},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 15},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 15},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 15},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 15},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 15},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 15},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 15},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 15},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 15},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 15},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 15},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 15},
  [143] = {.lex_state = 15},
  [144] = {.lex_state = 15},
  [145] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_process] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_channel] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_free] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_event] = ACTIONS(1),
    [anon_sym_query] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_EQ_EQ_GT] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_yield] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(138),
    [sym__declaration] = STATE(10),
    [sym_type_declaration] = STATE(10),
    [sym_channel_declaration] = STATE(10),
    [sym_free_declaration] = STATE(10),
    [sym_let_declaration] = STATE(10),
    [sym_event_declaration] = STATE(10),
    [sym_query_declaration] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_process] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_channel] = ACTIONS(11),
    [anon_sym_free] = ACTIONS(13),
    [anon_sym_let] = ACTIONS(15),
    [anon_sym_event] = ACTIONS(17),
    [anon_sym_query] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_COLON,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(65), 1,
      aux_sym_free_declaration_repeat1,
    ACTIONS(27), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(21), 11,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [34] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(21), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [61] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 11,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [91] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(41), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [115] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 8,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [151] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(31), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [175] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_type,
    ACTIONS(56), 1,
      anon_sym_channel,
    ACTIONS(59), 1,
      anon_sym_free,
    ACTIONS(62), 1,
      anon_sym_let,
    ACTIONS(65), 1,
      anon_sym_event,
    ACTIONS(68), 1,
      anon_sym_query,
    ACTIONS(51), 2,
      ts_builtin_sym_end,
      anon_sym_process,
    STATE(8), 8,
      sym__declaration,
      sym_type_declaration,
      sym_channel_declaration,
      sym_free_declaration,
      sym_let_declaration,
      sym_event_declaration,
      sym_query_declaration,
      aux_sym_source_file_repeat1,
  [211] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_EQ,
      anon_sym_LT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 11,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [239] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_type,
    ACTIONS(11), 1,
      anon_sym_channel,
    ACTIONS(13), 1,
      anon_sym_free,
    ACTIONS(15), 1,
      anon_sym_let,
    ACTIONS(17), 1,
      anon_sym_event,
    ACTIONS(19), 1,
      anon_sym_query,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      anon_sym_process,
    STATE(8), 8,
      sym__declaration,
      sym_type_declaration,
      sym_channel_declaration,
      sym_free_declaration,
      sym_let_declaration,
      sym_event_declaration,
      sym_query_declaration,
      aux_sym_source_file_repeat1,
  [277] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(77), 1,
      anon_sym_AMP_AMP,
    ACTIONS(79), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 6,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_EQ_EQ_GT,
  [317] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(77), 1,
      anon_sym_AMP_AMP,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 7,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [355] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(81), 13,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [379] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 3,
      anon_sym_EQ,
      anon_sym_GT,
      anon_sym_LT,
    ACTIONS(31), 11,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [405] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 8,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [441] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 9,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [475] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(33), 1,
      anon_sym_EQ,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(31), 10,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_LT_EQ,
      anon_sym_LT_GT,
      anon_sym_AMP_AMP,
      anon_sym_PIPE_PIPE,
      anon_sym_EQ_EQ_GT,
  [507] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(77), 1,
      anon_sym_AMP_AMP,
    ACTIONS(79), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    STATE(61), 1,
      aux_sym_query_repeat1,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(85), 2,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [552] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(77), 1,
      anon_sym_AMP_AMP,
    ACTIONS(79), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(91), 3,
      anon_sym_DOT,
      anon_sym_SEMI,
      anon_sym_LBRACK,
  [592] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(77), 1,
      anon_sym_AMP_AMP,
    ACTIONS(79), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(84), 1,
      aux_sym_predicate_term_repeat1,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
  [636] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_GT,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_GT_EQ,
    ACTIONS(47), 1,
      anon_sym_LT_EQ,
    ACTIONS(49), 1,
      anon_sym_LT_GT,
    ACTIONS(75), 1,
      anon_sym_EQ,
    ACTIONS(77), 1,
      anon_sym_AMP_AMP,
    ACTIONS(79), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(89), 1,
      anon_sym_EQ_EQ_GT,
    ACTIONS(35), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(97), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [675] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [689] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [745] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [759] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [773] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [787] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [815] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [829] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [857] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [871] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [885] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [899] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 8,
      ts_builtin_sym_end,
      anon_sym_process,
      anon_sym_type,
      anon_sym_channel,
      anon_sym_free,
      anon_sym_let,
      anon_sym_event,
      anon_sym_query,
  [913] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym_message_process,
    STATE(125), 1,
      sym_process,
    ACTIONS(133), 2,
      anon_sym_0,
      anon_sym_yield,
    ACTIONS(135), 2,
      anon_sym_in,
      anon_sym_out,
  [931] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_identifier,
    STATE(92), 1,
      sym_query,
    STATE(93), 1,
      sym_type_annotation,
    STATE(18), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [949] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym_message_process,
    STATE(117), 1,
      sym_process,
    ACTIONS(133), 2,
      anon_sym_0,
      anon_sym_yield,
    ACTIONS(135), 2,
      anon_sym_in,
      anon_sym_out,
  [967] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym_message_process,
    STATE(134), 1,
      sym_process,
    ACTIONS(133), 2,
      anon_sym_0,
      anon_sym_yield,
    ACTIONS(135), 2,
      anon_sym_in,
      anon_sym_out,
  [985] = 5,
    ACTIONS(3), 1,
      sym_comment,
    STATE(49), 1,
      sym_message_process,
    STATE(136), 1,
      sym_process,
    ACTIONS(133), 2,
      anon_sym_0,
      anon_sym_yield,
    ACTIONS(135), 2,
      anon_sym_in,
      anon_sym_out,
  [1003] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(78), 1,
      sym_query,
    STATE(18), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1018] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(91), 1,
      sym_message_process,
    ACTIONS(135), 2,
      anon_sym_in,
      anon_sym_out,
    ACTIONS(141), 2,
      anon_sym_0,
      anon_sym_yield,
  [1033] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(83), 1,
      sym_query,
    STATE(18), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1048] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(7), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1060] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(21), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1072] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    STATE(62), 1,
      aux_sym_process_repeat1,
    ACTIONS(143), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1086] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(6), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1098] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(19), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1110] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_SEMI,
    STATE(52), 1,
      aux_sym_query_repeat1,
    ACTIONS(91), 2,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1124] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(14), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1136] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(9), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1148] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(4), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1160] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(17), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1172] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(16), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1184] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(15), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1196] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(12), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1208] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(11), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1220] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(87), 1,
      anon_sym_SEMI,
    STATE(52), 1,
      aux_sym_query_repeat1,
    ACTIONS(150), 2,
      anon_sym_DOT,
      anon_sym_LBRACK,
  [1234] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      aux_sym_process_repeat1,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1248] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
    STATE(20), 3,
      sym__query_term,
      sym_predicate_term,
      sym_binary_term,
  [1260] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_SEMI,
    STATE(64), 1,
      aux_sym_process_repeat1,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1274] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_COLON,
    STATE(72), 1,
      aux_sym_free_declaration_repeat1,
  [1287] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(161), 1,
      anon_sym_COLON,
    STATE(72), 1,
      aux_sym_free_declaration_repeat1,
  [1300] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
  [1309] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(167), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      aux_sym_option_list_repeat1,
  [1322] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 1,
      anon_sym_DOT,
    ACTIONS(171), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_channel_declaration_repeat1,
  [1335] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_DOT,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
    STATE(140), 1,
      sym_option_list,
  [1348] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(101), 1,
      sym__type_identifier,
    ACTIONS(178), 2,
      anon_sym_channel,
      sym_identifier,
  [1359] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_COLON,
    STATE(72), 1,
      aux_sym_free_declaration_repeat1,
  [1372] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(187), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_type_list_repeat1,
  [1385] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(25), 1,
      anon_sym_COLON,
    STATE(65), 1,
      aux_sym_free_declaration_repeat1,
  [1398] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    STATE(103), 1,
      aux_sym_parameter_list_repeat1,
  [1411] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(195), 1,
      anon_sym_SEMI,
    STATE(85), 1,
      aux_sym_query_declaration_repeat1,
  [1424] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_COMMA,
    ACTIONS(197), 1,
      anon_sym_RPAREN,
    STATE(73), 1,
      aux_sym_type_list_repeat1,
  [1437] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
    ACTIONS(199), 1,
      anon_sym_DOT,
    STATE(139), 1,
      sym_option_list,
  [1450] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1459] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(79), 1,
      sym__type_identifier,
    ACTIONS(203), 2,
      anon_sym_channel,
      sym_identifier,
  [1470] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(77), 1,
      sym__type_identifier,
    ACTIONS(205), 2,
      anon_sym_channel,
      sym_identifier,
  [1481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(99), 1,
      sym__type_identifier,
    ACTIONS(207), 2,
      anon_sym_channel,
      sym_identifier,
  [1492] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
    ACTIONS(209), 1,
      anon_sym_DOT,
    STATE(118), 1,
      sym_option_list,
  [1505] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_COMMA,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
    STATE(98), 1,
      aux_sym_predicate_term_repeat1,
  [1518] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(213), 1,
      anon_sym_COMMA,
    ACTIONS(216), 1,
      anon_sym_SEMI,
    STATE(85), 1,
      aux_sym_query_declaration_repeat1,
  [1531] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(165), 1,
      anon_sym_COMMA,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_option_list_repeat1,
  [1544] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(70), 1,
      sym__type_identifier,
    ACTIONS(220), 2,
      anon_sym_channel,
      sym_identifier,
  [1555] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_parameter_list_repeat1,
  [1568] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 1,
      anon_sym_DOT,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_channel_declaration_repeat1,
  [1581] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_RPAREN,
    STATE(90), 1,
      aux_sym_type_list_repeat1,
  [1594] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_SEMI,
  [1603] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
    ACTIONS(236), 1,
      anon_sym_DOT,
    STATE(119), 1,
      sym_option_list,
  [1616] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 1,
      anon_sym_COMMA,
    ACTIONS(238), 1,
      anon_sym_SEMI,
    STATE(76), 1,
      aux_sym_query_declaration_repeat1,
  [1629] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_DOT,
    ACTIONS(242), 1,
      anon_sym_LPAREN,
    STATE(115), 1,
      sym_type_list,
  [1642] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_EQ,
    ACTIONS(246), 1,
      anon_sym_LPAREN,
    STATE(129), 1,
      sym_parameter_list,
  [1655] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_COLON,
    STATE(66), 1,
      aux_sym_free_declaration_repeat1,
  [1668] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_DOT,
    STATE(89), 1,
      aux_sym_channel_declaration_repeat1,
  [1681] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 1,
      anon_sym_RPAREN,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    STATE(98), 1,
      aux_sym_predicate_term_repeat1,
  [1694] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_RPAREN,
  [1703] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(109), 1,
      sym__type_identifier,
    ACTIONS(257), 2,
      anon_sym_channel,
      sym_identifier,
  [1714] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_LBRACK,
    ACTIONS(259), 1,
      anon_sym_DOT,
    STATE(126), 1,
      sym_option_list,
  [1727] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
    STATE(102), 1,
      aux_sym_option_list_repeat1,
  [1740] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_parameter_list_repeat1,
  [1753] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_identifier,
    STATE(75), 1,
      sym_type_annotation,
  [1763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_DOT,
      anon_sym_COMMA,
  [1771] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_identifier,
    STATE(111), 1,
      sym_type_annotation,
  [1781] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1789] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_identifier,
    STATE(130), 1,
      sym__process_term,
  [1799] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1807] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      sym_identifier,
    STATE(123), 1,
      sym__process_term,
  [1817] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [1825] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [1833] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      sym_identifier,
    STATE(112), 1,
      sym_type_annotation,
  [1843] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_COMMA,
      anon_sym_COLON,
  [1851] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_DOT,
  [1858] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_identifier,
  [1865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      ts_builtin_sym_end,
  [1872] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_DOT,
  [1879] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_DOT,
  [1886] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_private,
  [1893] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_DOT,
  [1900] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_private,
  [1907] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
  [1914] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      anon_sym_EQ,
  [1921] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_DOT,
  [1928] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_DOT,
  [1935] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_identifier,
  [1942] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      anon_sym_EQ,
  [1949] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_EQ,
  [1956] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      anon_sym_COMMA,
  [1963] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      anon_sym_DOT,
  [1970] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(312), 1,
      anon_sym_DOT,
  [1977] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(314), 1,
      sym_identifier,
  [1984] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(316), 1,
      anon_sym_DOT,
  [1991] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(318), 1,
      anon_sym_DOT,
  [1998] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(320), 1,
      ts_builtin_sym_end,
  [2005] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(322), 1,
      anon_sym_LPAREN,
  [2012] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
  [2019] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(326), 1,
      anon_sym_DOT,
  [2026] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(328), 1,
      anon_sym_DOT,
  [2033] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(330), 1,
      anon_sym_DOT,
  [2040] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(332), 1,
      sym_identifier,
  [2047] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(334), 1,
      sym_identifier,
  [2054] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(336), 1,
      sym_identifier,
  [2061] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(338), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 34,
  [SMALL_STATE(4)] = 61,
  [SMALL_STATE(5)] = 91,
  [SMALL_STATE(6)] = 115,
  [SMALL_STATE(7)] = 151,
  [SMALL_STATE(8)] = 175,
  [SMALL_STATE(9)] = 211,
  [SMALL_STATE(10)] = 239,
  [SMALL_STATE(11)] = 277,
  [SMALL_STATE(12)] = 317,
  [SMALL_STATE(13)] = 355,
  [SMALL_STATE(14)] = 379,
  [SMALL_STATE(15)] = 405,
  [SMALL_STATE(16)] = 441,
  [SMALL_STATE(17)] = 475,
  [SMALL_STATE(18)] = 507,
  [SMALL_STATE(19)] = 552,
  [SMALL_STATE(20)] = 592,
  [SMALL_STATE(21)] = 636,
  [SMALL_STATE(22)] = 675,
  [SMALL_STATE(23)] = 689,
  [SMALL_STATE(24)] = 703,
  [SMALL_STATE(25)] = 717,
  [SMALL_STATE(26)] = 731,
  [SMALL_STATE(27)] = 745,
  [SMALL_STATE(28)] = 759,
  [SMALL_STATE(29)] = 773,
  [SMALL_STATE(30)] = 787,
  [SMALL_STATE(31)] = 801,
  [SMALL_STATE(32)] = 815,
  [SMALL_STATE(33)] = 829,
  [SMALL_STATE(34)] = 843,
  [SMALL_STATE(35)] = 857,
  [SMALL_STATE(36)] = 871,
  [SMALL_STATE(37)] = 885,
  [SMALL_STATE(38)] = 899,
  [SMALL_STATE(39)] = 913,
  [SMALL_STATE(40)] = 931,
  [SMALL_STATE(41)] = 949,
  [SMALL_STATE(42)] = 967,
  [SMALL_STATE(43)] = 985,
  [SMALL_STATE(44)] = 1003,
  [SMALL_STATE(45)] = 1018,
  [SMALL_STATE(46)] = 1033,
  [SMALL_STATE(47)] = 1048,
  [SMALL_STATE(48)] = 1060,
  [SMALL_STATE(49)] = 1072,
  [SMALL_STATE(50)] = 1086,
  [SMALL_STATE(51)] = 1098,
  [SMALL_STATE(52)] = 1110,
  [SMALL_STATE(53)] = 1124,
  [SMALL_STATE(54)] = 1136,
  [SMALL_STATE(55)] = 1148,
  [SMALL_STATE(56)] = 1160,
  [SMALL_STATE(57)] = 1172,
  [SMALL_STATE(58)] = 1184,
  [SMALL_STATE(59)] = 1196,
  [SMALL_STATE(60)] = 1208,
  [SMALL_STATE(61)] = 1220,
  [SMALL_STATE(62)] = 1234,
  [SMALL_STATE(63)] = 1248,
  [SMALL_STATE(64)] = 1260,
  [SMALL_STATE(65)] = 1274,
  [SMALL_STATE(66)] = 1287,
  [SMALL_STATE(67)] = 1300,
  [SMALL_STATE(68)] = 1309,
  [SMALL_STATE(69)] = 1322,
  [SMALL_STATE(70)] = 1335,
  [SMALL_STATE(71)] = 1348,
  [SMALL_STATE(72)] = 1359,
  [SMALL_STATE(73)] = 1372,
  [SMALL_STATE(74)] = 1385,
  [SMALL_STATE(75)] = 1398,
  [SMALL_STATE(76)] = 1411,
  [SMALL_STATE(77)] = 1424,
  [SMALL_STATE(78)] = 1437,
  [SMALL_STATE(79)] = 1450,
  [SMALL_STATE(80)] = 1459,
  [SMALL_STATE(81)] = 1470,
  [SMALL_STATE(82)] = 1481,
  [SMALL_STATE(83)] = 1492,
  [SMALL_STATE(84)] = 1505,
  [SMALL_STATE(85)] = 1518,
  [SMALL_STATE(86)] = 1531,
  [SMALL_STATE(87)] = 1544,
  [SMALL_STATE(88)] = 1555,
  [SMALL_STATE(89)] = 1568,
  [SMALL_STATE(90)] = 1581,
  [SMALL_STATE(91)] = 1594,
  [SMALL_STATE(92)] = 1603,
  [SMALL_STATE(93)] = 1616,
  [SMALL_STATE(94)] = 1629,
  [SMALL_STATE(95)] = 1642,
  [SMALL_STATE(96)] = 1655,
  [SMALL_STATE(97)] = 1668,
  [SMALL_STATE(98)] = 1681,
  [SMALL_STATE(99)] = 1694,
  [SMALL_STATE(100)] = 1703,
  [SMALL_STATE(101)] = 1714,
  [SMALL_STATE(102)] = 1727,
  [SMALL_STATE(103)] = 1740,
  [SMALL_STATE(104)] = 1753,
  [SMALL_STATE(105)] = 1763,
  [SMALL_STATE(106)] = 1771,
  [SMALL_STATE(107)] = 1781,
  [SMALL_STATE(108)] = 1789,
  [SMALL_STATE(109)] = 1799,
  [SMALL_STATE(110)] = 1807,
  [SMALL_STATE(111)] = 1817,
  [SMALL_STATE(112)] = 1825,
  [SMALL_STATE(113)] = 1833,
  [SMALL_STATE(114)] = 1843,
  [SMALL_STATE(115)] = 1851,
  [SMALL_STATE(116)] = 1858,
  [SMALL_STATE(117)] = 1865,
  [SMALL_STATE(118)] = 1872,
  [SMALL_STATE(119)] = 1879,
  [SMALL_STATE(120)] = 1886,
  [SMALL_STATE(121)] = 1893,
  [SMALL_STATE(122)] = 1900,
  [SMALL_STATE(123)] = 1907,
  [SMALL_STATE(124)] = 1914,
  [SMALL_STATE(125)] = 1921,
  [SMALL_STATE(126)] = 1928,
  [SMALL_STATE(127)] = 1935,
  [SMALL_STATE(128)] = 1942,
  [SMALL_STATE(129)] = 1949,
  [SMALL_STATE(130)] = 1956,
  [SMALL_STATE(131)] = 1963,
  [SMALL_STATE(132)] = 1970,
  [SMALL_STATE(133)] = 1977,
  [SMALL_STATE(134)] = 1984,
  [SMALL_STATE(135)] = 1991,
  [SMALL_STATE(136)] = 1998,
  [SMALL_STATE(137)] = 2005,
  [SMALL_STATE(138)] = 2012,
  [SMALL_STATE(139)] = 2019,
  [SMALL_STATE(140)] = 2026,
  [SMALL_STATE(141)] = 2033,
  [SMALL_STATE(142)] = 2040,
  [SMALL_STATE(143)] = 2047,
  [SMALL_STATE(144)] = 2054,
  [SMALL_STATE(145)] = 2061,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__query_term, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__query_term, 1),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_term, 3, .production_id = 9),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_term, 3, .production_id = 9),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_term, 4, .production_id = 12),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate_term, 4, .production_id = 12),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(127),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(145),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(144),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(143),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(142),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_predicate_term, 5, .production_id = 18),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_predicate_term, 5, .production_id = 18),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_predicate_term_repeat1, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 6, .production_id = 15),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_declaration, 4, .production_id = 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 5, .production_id = 14),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 7, .production_id = 23),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 6, .production_id = 20),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 6, .production_id = 19),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_declaration, 3, .production_id = 1),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_declaration, 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 6, .production_id = 17),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 5, .production_id = 10),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 4, .production_id = 8),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_declaration, 4),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query_declaration, 3, .production_id = 2),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 7, .production_id = 22),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_declaration, 5, .production_id = 11),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_free_declaration, 6, .production_id = 16),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_event_declaration, 3, .production_id = 1),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_repeat1, 2), SHIFT_REPEAT(51),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_query, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_process, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_process_repeat1, 2),
  [156] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_process_repeat1, 2), SHIFT_REPEAT(45),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_process, 6, .production_id = 21),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_channel_declaration_repeat1, 2),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_channel_declaration_repeat1, 2), SHIFT_REPEAT(133),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_free_declaration_repeat1, 2, .production_id = 3), SHIFT_REPEAT(116),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_free_declaration_repeat1, 2, .production_id = 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 3, .production_id = 5),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_query_declaration_repeat1, 2, .production_id = 7), SHIFT_REPEAT(113),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_declaration_repeat1, 2, .production_id = 7),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2), SHIFT_REPEAT(106),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2), SHIFT_REPEAT(100),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_type_list_repeat1, 2),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [252] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_predicate_term_repeat1, 2), SHIFT_REPEAT(48),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_annotation, 4, .production_id = 13),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_option_list_repeat1, 2), SHIFT_REPEAT(120),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_option_list_repeat1, 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_query_declaration_repeat1, 2, .production_id = 6),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_free_declaration_repeat1, 2, .production_id = 1),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_list, 3),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 3),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 4),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [322] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [324] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_option_list, 4),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_proverif() {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
